#!/bin/sh
# Looks for a suitable tclsh or jimsh in the PATH
# If not found, builds a bootstrap jimsh from source
PATH="$PATH:$(pwd)"
tclsh=$(which jimsh 2>/dev/null || which tclsh8.5 2>/dev/null || which tclsh8.6 2>/dev/null || which jimsh0 2>/dev/null)
if [ -z "$tclsh" ]; then
	echo 1>&2 "No installed jimsh or tclsh, building local bootstrap jimsh0"
	${CC_FOR_BUILD:-cc} -o $(pwd)/jimsh0 $(dirname "$0")/jimsh0.c || exit 1
	tclsh="$(pwd)/jimsh0"
fi
echo $tclsh
